# Generated by Django 4.1.4 on 2023-11-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='age',
            field=models.IntegerField(),
        ),
    ]
